import type { IconType } from 'react-icons'
import {
  SiFlutter,
  SiDart,
  SiGoogleplay,
  SiAppstore,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiVite,
  SiNodedotjs,
  SiPython,
  SiGo,
  SiMongodb,
  SiPostgresql,
  SiFirebase,
  SiSupabase,
  SiGithub,
  SiDocker,
  SiN8N,
  SiSocketdotio,
  SiAndroidstudio,
  SiOpenai,
  SiGooglegemini,
  SiClaude,
} from 'react-icons/si'
import { FaAws, FaJava } from 'react-icons/fa'
import { VscVscode } from 'react-icons/vsc'
import {
  TbApi,
  TbBrain,
  TbCube,
  TbDatabase,
  TbDroplet,
  TbPackage,
  TbPointer,
  TbRocket,
  TbSql,
} from 'react-icons/tb'

/** Brand (or best-effort) icon for every skill in portfolio.json. */
export const SKILL_ICONS: Record<string, IconType> = {
  Flutter: SiFlutter,
  Dart: SiDart,
  BLOC: TbCube,
  Riverpod: TbDroplet,
  Provider: TbPackage,
  'Play Store': SiGoogleplay,
  'App Store': SiAppstore,
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  'HTML / CSS': SiHtml5,
  Zustand: TbCube,
  Vite: SiVite,
  'Node.js': SiNodedotjs,
  Python: SiPython,
  GoLang: SiGo,
  JAVA: FaJava,
  'REST API': TbApi,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  Firebase: SiFirebase,
  Supabase: SiSupabase,
  SQL: TbSql,
  'Git / GitHub': SiGithub,
  AWS: FaAws,
  Docker: SiDocker,
  N8N: SiN8N,
  'API Integration': TbApi,
  'Socket.io': SiSocketdotio,
  'RAG Systems': TbBrain,
  Pinecone: TbDatabase,
  'VS Code': VscVscode,
  'Android Studio': SiAndroidstudio,
  'Claude Code': SiClaude,
  Antigravity: TbRocket,
  Codex: SiOpenai,
  Cursor: TbPointer,
  ChatGPT: SiOpenai,
  Gemini: SiGooglegemini,
}
